services:
  backend:
    build: ./backend
    ports:
      - "8081:8080"
    networks:
      - calendar-net
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/todo
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - SECRET=MzI3NzQ0NzQ4NjcyNDk3MzI5Nzk3NzY2OTQ2MzIzNjY4Nzg5Njk5ODc0NzY2Nzc4NTYzNzQ3Njc5NjY0OTY5Mzc2ODMzNjk5NTg1NzUyOTY0Mzk2OTU2MzY1MzQ5NDY5Nzg1NTM3NzQ2ODk5MjQzNTg2NDg4ODM0NTM5OTkxNzY2MTY4NjE0MjU3Nzc0NzY1MzA1NjE0NzY0NTg1Mzc5MjM5NzM0NTY3NTc0OTc2NjE4NDYyMjI1NTk0OTU4NzQ4MTM5MTg5NjcxNzk2MjE3NzQ5NzUzNzA2MTMxNjk2OTIwNTI5OTI5MzQ1MjY2MDc2NjYxMjQwNjY2NzQ5Njk2NTUwNTMxMTg5OTc4NDc0NDQ3NjkzNjcyNTIwNTg3MjcxMzA5NTg4MzQwNjYzNjM3Nzg2NjkxNzMwMjYxNTA4MjYxOTkwNDg0ODk2MTI5MjQ2MTg3MTMwMjcxMzQwMDQy
      - JWT_TIME=900000
      - RT_TIME=259200000
      - GOOGLE_CLIENT_ID=968754896902-g62j49a9a6o0kaepkkseos9dn04ecrpj.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - FACEBOOK_CLIENT_ID=2558253521030600
      - FACEBOOK_CLIENT_SECRET=508142feb71d12faa2e86d8f7d601a6f
    command: ["sh", "-c", "mvn clean package -DskipTests && java -jar target/*.jar"]

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - todo-db-data:/var/lib/postgresql/data
    networks:
      - calendar-net
    ports:
      - "5432:5432"

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - calendar-net
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  calendar-net:
    driver: bridge

volumes:
  todo-db-data:
