CREATE TABLE refresh_tokens
(
    id                   BIGINT generated by default as identity NOT NULL,
    token                VARCHAR(255) NULL,
    username             VARCHAR(255) NULL,
    expiration_timestamp timestamp(0) NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);